dist: trusty
language: python
python:
- '3.6'
install:
  - pip install pipenv
  - pipenv sync
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
script:
  - pipenv run behave
